domain-needed                                                    # Don't forward plain names without dots (like 'printer')
bogus-priv                                                       # Block reverse lookups for private IP ranges
no-resolv                                                        # Don't use /etc/resolv.conf for upstream DNS
server=173.203.4.8
server=173.203.4.9
local=/td2.com/
bind-dynamic
interface=*
expand-hosts                                                     # Add domain suffix to hosts in /etc/hosts automatically
domain=td2.com                                                   # Set the default local domain
# Maximum number of concurrent forwarded DNS queries
dns-forward-max=10000

# Cache size for DNS responses
cache-size=1000

# Logging (optional for monitoring)
log-queries
#log-facility=/var/log/dnsmasq.log

# ----------------------------
# Safety / miscellaneous
# ----------------------------

# Prevent bogus queries for non-FQDN
strict-order

no-hosts
addn-hosts=/etc/dnsmasq.hosts
